### ISSUE TITLE
Ansicht der Filme/Serien (Liste-Fanart etc.) in den Einstellungen ändern

### ISSUE THREAD

**Issue by Yaqwa** [watchone/Downloads#10]
Sorry wenn ich Lastship nochmal anspreche aber dort gab es ein tolles Feature wo man für alle Sachen (Filme/Serien/Staffeln/Episoden) eine gewisse Ansicht in den Werkzeugen als Standard auswählen konnte. Gibt es die Möglichkeit dies auch in xship zu implementieren?

**Comment by watchone** [comment]
xShip ist und wird kein LastShip.
Was u.a. solche Erweiterungen bringt, das sieht man daran wie "schnell" LastShip ist.
