### ISSUE TITLE
Komt einen neue update fur Xship?

### ISSUE THREAD

**Issue by FransGamer** [watchone/Downloads#11]

**Comment by watchone** [comment]
Xship prüft bei jedem Kodi Start ob ein Update verfügbar ist und wenn ja wird eines gemacht. 
Es gibt nicht immer ein Update, ist ja auch nicht immer nötig -:)
Sobald einige ~nightly's zusammen gekommen sind gibt es auch wieder eine neu .zip Datei zum Downloadden

**Comment by FransGamer** [comment]
Wert Xship dan auch geupdated vom KDC repo?

**Comment by watchone** [comment]
Wir bieten kein REPO an, denn xShip braucht kein REPO nur die ZIP installieren reicht aus.
https://github.com/watchone/Downloads
