### ISSUE TITLE
Stockende Filmlisten

### ISSUE THREAD

**Issue by fankloano** [watchone/Downloads#13]
Hallo,
habe das Problem, dass xShip sobald ich einen anderen Skin als den Standardskin verwende ziemlich langsam wird. Sobald ich eine Filmliste anzeigen lasse dauert das wechseln von einem Film zum anderen ca. 2 Sekunden. Benutze den Skin Arctic Zephyr reloaded, bei anderen Addons (hab gestern auch xStream getestet) zeigt sich das Problem nicht. Habe noch 3 andere Skins getestet, Amber, Rapier, HorizonV, überall dasselbe Problem, im Standardskin Estuary läuft xShip aber flüssig.
Die anzuzeigenden Infos (im Addon und im Skin) hab ich auch schon reduziert, konnte aber keine Besserung erkennen. 
Der Serienbereich läuft besser, nahezu flüssig.
Kodi 19 läuft direkt auf einem Philips 7354/12, der müsste das doch locker packen?
Vielleicht habt ihr ja einen Tipp der da helfen könnte. Vielen Dank!

**Comment by watchone** [comment]
Da wir nicht wissen wie diese Skins aufgebaut sind und auch keine Zeit haben die alle zu testen können wir keine Aussage dazu machen und das Problem zu orten.
