### ISSUE TITLE
Fehler im kodi log

### ISSUE THREAD

**Issue by polojoe** [watchone/Downloads#19]
Ich habe folgende Fehler im kodi.log
[Errno 2] No such file or directory: '/storage/.kodi/addons/script.module.urlresolver/Addon.xml' - Exception
[Errno 2] No such file or directory: '/storage/.kodi/addons/plugin.video.xship/Addon.xml' - Exception 

Wenn ich in der service.py die Zeile 108 auf
addon_xml = os.path.join(ADDON_PATH % ADDONID, '**a**ddon.xml')
ändere, ist der Fehler verschwunden.

**Comment by watchone** [comment]
Hi,
welche Kodiversion - welches Betriebsystem?

in version="2021.05.26~nightly2" geändert.

**Comment by polojoe** [comment]
danke, rpi4 libreelec 10 beta kodi 19.1
