### ISSUE TITLE
Wiedergabepunkt

### ISSUE THREAD

**Issue by jens2311** [watchone/Downloads#21]
Hallo, eine Frage zur Benutzung von XShip in Verbindung mit dem TheMovieDb Helper. Wenn ich einen Film aus der Kodi Bibliothek schaue, diesen zwischendrin beende und ihn später fortsetzen möchte fängt das immer von Anfang an.
Ich habe mal zum Test XStream als Player im TheMovieDb Helper gesetzt, da geht ein kleines Fenster auf wo man wählen kann den entsprechenden Startpunkt (Zeit) oder von Anfang an.
Muss ich in XShip etwas einstellen oder ist das hier generell nicht möglich.

Gruß eemily

**Comment by watchone** [comment]
fix in version="2021.06.04~nightly2"

**Comment by jens2311** [comment]
Danke für den Fix. Funktioniert bei mir nur wenn ich den Film stoppe und anschließend sofort wieder in der Bibliothek starte, dann kommt die Abfrage. Sobald ich aber zwischendurch einen anderen schaue oder Kodi beende fängt es immer wieder von vorne an.
Oder ich mache hier etwas falsch?
Gruß eemily

**Comment by watchone** [comment]
@jens2311 
Das von dir geschilderte Fehlerbild kann ich nicht reproduzieren. 
Im Gegenteil - egal ob Kodi beendet wir, ob zwischendurch ein anderer Film läuft - der Wiedergabepunkt ist immer korrekt. Nicht nur dann wenn ich über die Suche vom helper oder xship gehe, auch aus den Favoriten heraus funktioniert es.
Bibliothek  nutze ich nicht.
