### ISSUE TITLE
kinoger

### ISSUE THREAD

**Issue by demex2008** [watchone/Downloads#22]
hallo von kinoger werden nur
 ninjastream, kinoger FSST,gefunden immer in 480.
in xstream finde ich auch FSST ,aber auch kinoger.re und bei beiden kann man 1080 wählen.
habe getestet mit a quite place, jumanji, tom & jerry, army of dead, Raya, Mortal Kombat. Kinoger.FSST immer nur 480p
wäre toll wenn  man FSST auch in 1080p wählen könnte
vieleicht kannst mal nachschauen.
mfg.
ps.Ansonsten finde ich die App toll gute Arbeit

**Comment by watchone** [comment]
Danke für den Hinweis!
