### ISSUE TITLE
Danke für den Hinweis!

### ISSUE THREAD

**Issue by demex2008** [watchone/Downloads#24]
Danke für den Hinweis!

kinoger.re nur 720p
kinoger.csst immer nur 480
kinoger.fsst immer nur 480
Ninjastream startet, bleibt stehen,startet bleibt stehen,usw

**Comment by watchone** [comment]
Warum wird nochmal ein neues Thema zum gleichen Problem erstellt?
Wenn du Nachfragen hast, dann bitte im alten Thema!
