### ISSUE TITLE
Xship & xbox

### ISSUE THREAD

**Issue by demex2008** [watchone/Downloads#25]
Hallo nutze kodi zur Zeit auf der Xbox,und Android Handy.
Nun ist es so wenn ich auf der xbox in Filme liste Popularität Gozilla vs Kong auswähle werden schön alle Sites mit Hoster aufgelistet,beende ich es dann nund starte die Suche nomals wird nichts mehr gefunden.dann muss ich die Konsole neu starten.Bei Anderen Filmen passiert das nicht.
Auf dem Handy passiert das nicht.
Also nur auf der Xbox der eine Filme
vielleicht hast du da ein Tipp
mfg.

**Comment by watchone** [comment]
Mangels xBox kann der Fehler nicht nachgestellt werden.
