### ISSUE TITLE
Kein Stream Startet

### ISSUE THREAD

**Issue by Reichi00** [watchone/Downloads#26]
Hi
Ich habe seit heute das Problem,  dass kein Stream mehr startet. Wirklich keiner mehr.
Daraufhin habe ich zum Test Kodi neu gemacht und Xship installiert.  Trotzdem das gleiche Problem. 
Dns ändern hatte ich auch getestet. 

XShip version 2021.06.20 nightly1
Urlresolver version 2021.06.18 nightly 
Kofi 19.1
Android 9

**Comment by sKippah** [comment]
Ich würde mal das Log lesen. Da sollte eine entsprechende Fehlermeldung zu auftauchen.
Sowas hilft dem Coder immer ungemein

**Comment by Reichi00** [comment]
ERROR <general>: [ Xship DEBUG ]: b'Error expected an indented block (player.py, line 358)' (ENCODED)
2021-06-21 22:38:24.041 T:9093     

INFO <general>: CPythonInvoker(8, /storage/emulated/0/Android/data/org.xbmc.kodinerds/files/.kodi/addons/plugin.video.xship/default.py): script successfully run
2021-06-21 22:38:24.210 T:9093     

INFO <general>: Python interpreter stopped
2021-06-21 22:38:24.225 T:8172    

ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.xship/?action=playItem&title=Die+Verurteilten&source=%5B%7B%22direct%22%3A+true%2C+%22language%22%3A+%22de%22%2C+%22quality%22%3A+%221080p%22%2C+%22source%22%3A+%22fsst.online%22%2C+%22url%22%3A+%22https%3A%2F%2Fwww.secvideo1.online%2Fget_file%2F4%2Fcd05fa0c1d4b732a711eeb53e9bc0619cd185b21d0%2F201000%2F201176%2F201176.mp4%2F%22%2C+%22provider%22%3A+%22kinoger%22%2C+%22priority%22%3A+1%2C+%22label%22%3A+%2203+%7C+%5BB%5DKINOGER%5B%2FB%5D+%7C+FSST+%7C+%5BB%5D%5BI%5D1080P+%5B%2FI%5D%5B%2FB%5D+%22%7D%5D]
2021-06-21 22:38:28.503 T:8172     

INFO <general>: CWinSystemAndroid::DestroyWindow
2021-06-21 22:38:28.798 T:27906 

WARNING <general>: CPeripheralBusAndroid: failed to update input device with ID 2 because it couldn't be found

Besser konnte ich es leider nicht einfügen. Mache alles mit einem Handy

**Comment by watchone** [comment]
mit Version "2021.06.21~nightly1 behoben.
Sind gestern beim editieren der player.py ein paar tabs verloren gegangen. Sorry!

**Comment by Reichi00** [comment]
Ach nicht dafür. Es kann immer mal was passieren. Danke für die schnelle Hilfe und danke für das tolle Addon.
