### ISSUE TITLE
Viele Streams nicht verfübar.

### ISSUE THREAD

**Issue by KlitschkoS** [watchone/Downloads#27]
Hallo, ich habe folgendes Anliegen: Wenn ich versuche etwas zu schauen, sagt er mir immer es sei keine Streams vorhanden. Es sind keine No Name Filme oder so. Das meiste weiß ich gucken möchte, funktioniert nicht. Bitte um Rückmeldung.

**Comment by kasi45** [comment]
Hier meine Rückmeldung:
Meine Glaskugel habe ich gerade verlegt, so das ich nicht erkennen kann welche Filme von welcher Anbieterseite bei dir nicht gehen.
Zu allen Filmen die ich schauen möchte, da findet sich meist mehrere Streams die funktionieren.

**Comment by watchone** [comment]
Hier meine Rückmeldung!
Leider habe ich meine Glaskugel verlegt so dass ich nicht sehen kann zu welchen Filme von welcher Anbieterseite bei dir keine funktionierenden Streams gefunden werden.
Zu allen Filmen die ich sehen möchte, da finden sich meist mehrere Streams die funktionieren.

**Comment by KlitschkoS** [comment]
Ich glaube ich habe mich etwas falsch ausgedruckt. Ich meine damit, z.b in meinem Fall viele Serien. Alle Serien die ich gucken möchte sind nicht Verfügbar, jedoch auf deren Seite schon. Wie kommt es dazu? Schließlich werden ja die streams von den Seiten genommen.

**Comment by sKippah** [comment]
Du bist so super ungenau in deiner Beschreibung, dass ich als Dev die Hände über dem Kopf zusammenschlagen würde.

"jedoch auf deren Seite schon" - Auf WESSEN Seite?

Vllt mal n Log posten innerhalb des Codes (<>) Tags, dann kann man mit deiner Aussage evtl. auch was anfangen.

Du musst dich immer in die Lage einer anderen Person versetzen. Die weiß nicht was du weißt und du solltest versuchen dein Problem so gut wie möglich zu beschreiben, evtl mit Fehlerquelle = Log.

Ich gehe mal davon aus das du mit der Serienseite "s.to" meinst. In dem Fall würde ich zuerst mal die Login Daten auf Richtigkeit überprüfen - Mir hat hier tatsächlich geholfen die Login Daten so simpel wie möglich zu halten. Irgendwie hatte XShip Probleme mit meinem verkomplizierten PW.

Wenn die Daten stimmen, mal versuchen eine andere URL zu nehmen und Kodi neu starten.

Ansonsten Kodi Log mit den XShip Daten posten, das wird @watchone 
sicher helfen, dir bei deinem Problem zu helfen!
btw. bei mir funktioniert alles Tadellos

**Comment by KlitschkoS** [comment]
An den Daten liegt es nicht. Wie kann man denn eine andere "URL" nehmen? Zudem weiß ich auch nicht wie ich Ein Log einsehen kann. Wenn bei dir alles tadellos funktioniert, kannst du mal ausprobieren ob bei dir "Kuroko's Basketball" Bei dir funktioniert? https://serienstream.sx/serie/stream/kuroko-no-basket Dann würde ich wissen, ob es an mir liegt. Ich hatte keine Ahnung wie ich ein Log posten soll deshalb im txt. Document. Ich bedanke mich für die Vorschläge.
[kodi log.txt](https://github.com/watchone/Downloads/files/6804564/kodi.log.txt)

**Comment by watchone** [comment]
@KlitschkoS  
wenn du ernsthafte Hilfe bei einem Problem möchtest, dann solltest du vor dem posten von deiner Anfrage etwas mehr Gedanken machen was du schreibst. Auch sollte man dabei die passende Umgangsform - wie Höflichkeit und so - wählen.
Keiner der Dev's ist hier ein bezahlter Dienstleister und du bist kein zahlender Kunde.

In seinem Beitrag hat @sKippah  dir ja schon ein paar Hinweise dazu gegeben was inhaltlich bei einer Problemsituation man mitteilen müsste.

Da du in deinem letzten Beitrag ein konkretes Beispiel benannt hast und so wie es sich gehört dazu auch gleich einen Link beigefügt hast, da kann ich dir dazu eine Antwort geben.

zuerst - es ist kein xShip Problem bzw. Fehler!

"Kuroko's Basketball" - wird ja als Serie schon mal gefunden, mit all seinen Staffeln/Episoden
Was die Datenbank (Trakt) aber nicht liefert sind Aliase zu dem Titel. Die sind bei trakt.tv nicht eingepflegt.
Hier siehst du mal unter welchen Aliases der Titel noch geführt wird: https://www.wikidata.org/wiki/Q482715
S.to nutzt "Kuroko no Basket" - das kennt trakt.tv nicht und somit kann xShip  auch nichts finden.

mfg watchone

**Comment by watchone** [comment]
![Unbenannt](https://user-images.githubusercontent.com/82899367/125496520-895fa897-d1cc-47bb-9bd1-c87cd728860e.JPG)

**Comment by sKippah** [comment]
Vllt liegts tatsächlich an einer nicht verfügbaren URL. Ich habe Kodi nur auf dem FireTV und kann keinen Screenshot machen aber vllt. magst du @watchone es mal fix erklären, wie man die URL wechselt. Eventuell ist dann Ruhe ;)

**Comment by watchone** [comment]
@sKippah 
In xShip musst du dich nicht um eine URL kümmern. Darum "kümmert" sich das Addon selber.

Ich habe noch eine weitere Möglichkeit gefunden zusätzliche Aliases für die Titel abzufragen. Damit werden nun auch Streams u.a. fur "Kuroko's Basketball" gefunden.

**Comment by watchone** [comment]
![Unbenannt](https://user-images.githubusercontent.com/82899367/125498553-24967fe5-8f5b-4147-90fb-2c0d5ae263aa.JPG)

**Comment by watchone** [comment]
Läuft!

**Comment by watchone** [comment]
Wird beim nächsten Update mit eingepflegt!

**Comment by KlitschkoS** [comment]
Okay, ich bedanke mich für die schnelle hilfe.

**Comment by watchone** [comment]
@KlitschkoS 

Bitte mal lesen: https://github.com/watchone/Downloads/blob/master/README.md

**Comment by KlitschkoS** [comment]
Sorry^^

**Comment by watchone** [comment]
<grins> zwischenzeitlich hat jemand bei trakt.tv die Aliases für "Kuroko's Basketball" eingepflegt.
Ich wollte etwas testen - ohne die neue Änderung - und bekam auf einmal Streams angezeigt. :-D
Danke an den Unbekannten!
