### ISSUE TITLE
Kurze Frage

### ISSUE THREAD

**Issue by KlitschkoS** [watchone/Downloads#28]
Ich bins wieder. Ich habe mich inzwischen gefragt, ob jeder bei trakt.tv aliases eintragen kann. Ich würde nämlich gerne helfen, aliases einzutragen.

**Comment by sKippah** [comment]
Da fragst du besser den Support von Trakt

**Comment by watchone** [comment]
mit der neuen Änderung werden auch die Aliases von tmdb genutzt und nur noch durch aliases von trakt.tv ergänzt wenn diese noch nicht in den aliases von tmdb vorhanden sind. Das alles ohne zusätzliche Abfragen an die Datenbanken - gegenüber der alten version von xShip - "nur" Parameter ergänzt
