### ISSUE TITLE
xship Werkzeuge

### ISSUE THREAD

**Issue by demex2008** [watchone/Downloads#32]
hallo habe ein kleinen fehler entdeckt unter wekzeuge
 [/B] Einstellungen
 [/B] Reset Settings 
da seht noch bei beiden das [/B] für die Fett schrift 
wollte es selbst ändern aber geht nicht
mfg
ps. super APP

**Comment by watchone** [comment]
Bitte lesen:
https://github.com/watchone/Downloads/blob/master/README.md
