### ISSUE TITLE
Add Index Site Streamkiste.tv

### ISSUE THREAD

**Issue by jonatan2010** [watchone/Downloads#33]
Bitte unterstützt die Index Seite Streamkiste.tv

Sie beinhaltet fast alle Serien und Filme, die es in deutscher Sprache gibt.

**Comment by watchone** [comment]
Aus Zeitgründen im Moment nicht umsetzbar

**Comment by jonatan2010** [comment]
Okay. Es eilt ja nicht. Wäre super, wenn es irgendwann in Zukunft möglich ist.
