### ISSUE TITLE
s.to problem/Streamtape problem

### ISSUE THREAD

**Issue by jonatan2010** [watchone/Downloads#36]
S.to Links werden entweder überhaupt nicht gefunden (Dragonball super Serie ab Folge 100 ungefähr) oder es wird nur ein einzelner Link gefunden, wo ein Wiedergabe Fehler kommt (stargate Atlantis Serie s.to Streamtape hoster)

S.to hat dragonball super in 5 Staffeln aufgeteilt. Eventuell liegt dieses problem daran.

Direkt auf der Webseite s.to funktioniert alles. Möglicherweise sind noch viele andere Webseiten betroffen.

Hinzu kommt, dass der hoster Streamtape auf der Webseite auch funktioniert, xship aber einen Wiedergabefehler anzeigt, bzw. Garnichts passiert, wenn man drauftippt. Der Stream startet einfach nicht bei xship.

**Comment by watchone** [comment]
https://github.com/watchone/Downloads/blob/master/README.md

**Comment by watchone** [comment]
Ohne konkrete Angaben und Beispiel wird nicht weiter reagiert
