### ISSUE TITLE
S.to Problem/streamtape problem

### ISSUE THREAD

**Issue by jonatan2010** [watchone/Downloads#38]
Bei s.to werden bei der Serie dragonball super nur die ersten 14 folgen gefunden, weil folge 15 in wahrheit staffel 2 folge 1 ist. Hier die links dazu:

https://s.to/serie/stream/dragonball-super/staffel-2/episode-1

https://streamtape.com/e/9b37dB7wMyTa8aq

Wie sie sehen können funktioniert alles, wenn man es im Browser, wie z.b. Firefox, eingibt. Aber xship findet keine links.

Nächstes Problem sind generell streamtape hoster links bei ALLEN Serien und Filmen!

Xship arbeitet kurz und das wars. Das Video wird nicht abgespielt. Auch hier liegt es wieder nur an xship, denn im browser, wie beispielsweise Firefox, wird das Video abgespielt. Auch hier wieder beispiellinks:

https://s.to/serie/stream/stargate-atlantis/staffel-1/episode-1

https://streamtape.com/e/dP7ZVl6wKZCkogz

Alles mit kodi 18 und kodi 19 getestet, selbes Ergebnis!
![Screenshot_20210915-091037_Firefox](https://user-images.githubusercontent.com/90136375/133388904-1d330949-5e48-4016-89d3-f3e7d85c73e2.png)
![Screenshot_20210915-091059_Firefox](https://user-images.githubusercontent.com/90136375/133388912-e8117e38-3728-4602-a75b-2cea8b04641c.png)
![Screenshot_20210915-091218_Firefox](https://user-images.githubusercontent.com/90136375/133388916-1f22b7bf-d8eb-497c-bcea-5232b3cba36a.png)
![Screenshot_20210915-091326_Firefox](https://user-images.githubusercontent.com/90136375/133388919-f189c4e7-7a1d-4c38-8c4f-c410b98431bc.png)
![Screenshot_20210915-091749_GoK_19 0](https://user-images.githubusercontent.com/90136375/133388930-7e0b219d-e2c4-4715-b1f8-b5a81908430c.png)

Screenshots habe ich auch angefügt, damit es dieses mal wirklich verstanden wird!

**Comment by sKippah** [comment]
Bei Fehlermeldung eher das Kodi Log einfügen denn irgendwelche übergroßen Bilder.

Stell dir mal vor ich gehe zum Arzt und erzähle dem: "Ich habe Schmerzen"
Wo denn? Ich habe Schmerzen? Meinst Du, dass das dem Arzt hilft?

Im Kodi Log steht alles was man Wissen muss.

Zur Fehlerfindung würde mir das hier, als Coder, Null helfen. 
Schön, in deinem Browser gehts und warum nicht in Kodi? 
Das kann an deinen Einstellungen liegen, an deiner Software Umgebung, irgendeinem anderen Program das "querschlägt" etc. 

Ohne Log kann man keinen Fehler finden!!!! Google hilft
Ich verstehe nicht, dass die Leute das nicht checken. bist ja nicht der erste. 
Irgendwie erwarten hier alle Wunder. Der XShip Coder ist wahrscheinlich ein Zauberer

**Comment by jonatan2010** [comment]
Bim ersten mal wurde meine Anfrage geschlossen, weil ich keine links angefügt habe. Das habe ich jetzt getan, wurde wieder geschlossen.

Bei dem streamtape Problem kommt keine fehlermeldung. Es was soll da im log stehen?

Dasselbe bei dem Serien Problem. Da kommt zwar die Meldung, dass nichts gefunden wurde, aber nicht die Meldung, dass etwas im log ist!

Habe ich mich denn wirklich nicht klar genug ausgedrückt, dass die Serie bei xship nur eine Staffel 1 mit ca. 130 folgen har, aber bei s.to die erste Staffel nur 14 folgen hat und die restlichen folgen dann in Staffel 2,3,4 und 5 drin sind?

Wtf ist da nicht verständlich?

**Comment by sKippah** [comment]
Mit solchen Antworten musst du dich nicht wunder. Das Tool ist free und du zeterst hier rum wie ne wildgewordene Mutti,
Wenns dir nicht gefällt nutz es nicht. Wenn du keine klare Fehlermeldung schicken kannst. Nutz es nicht.
Gratis Tool und Mega MiMiMi

**Comment by jonatan2010** [comment]
Ja, ich bin sauer, weil jetzt schon trotz glasklaren fehlerbeschreibungen meine anfragen mehrfach geschlossen wurden, ohne die Probleme zu beheben.

Wenn es geschlossen worden wäre mit der Nachricht, dass sie es checken, kein problem. Aber nicht so!

**Comment by sKippah** [comment]
Deine Fehlerbeschreibung ist alles andere als Glaskar. Alles was du machst ist zu schreiben, das dies nicht funktioniert, da aber schon mit übergroßen Fotos die die komplette Übersicht zerstören.
Ich würde es als Developer genau so machen.
Du schaffst keine Fehlermeldung = löschen

Such mal in Google nach Fehlerbeschreibung und wie man eine macht.

Anyway. Geht mich im Grunde nichts an. Da ich aber selbst im Software Bereich tätig bin, regen mich solche Posts wie deine einfach nur noch auf.
Du verlangst viel aber deine Infos sind nichtssagend.
Ich mag deinen Frust nicht weiter anschüren. Deswegen bin ich raus hier.

Über eines musst Du Dir aber bewusst sein. 
XShip ist Gratis. Da gibt es eine oder mehrere Personen die, GRATIS, eine Software zur Verfügung stellen, die es DIR ermöglicht FILME und SERIEN UMSONST anzusehen.
Und alles was Du kannst ist dich auch widerlichste Art und Weise zu beschweren.

**Comment by jonatan2010** [comment]
Ich hab kein problem, wieder wie früher per castify APP an meinen chromecast zu casten, zumal ich da auch streamkiste.tv nutzen kann. Das funktioniert webigstens ordebtlich. 

Es war so einfach ein wenig bequemer. Wenn aber vieles nicht (mehr) funktioniert, hat es keinen Sinn mehr.

Ja, ich bin kein super kodi freak, eher ein normaler user, der von logs und sowas keine Ahnung hat.

Es wurden übrigens nirgends logs angefordert. (Außer von dir)

Ich wollte durch die Screenshots nur zeigen ,dass es wirklich nur am addon liegt. Das die gleich so groß werden, kann ich ja auch nichts für.
