### ISSUE TITLE
Streamtape keine reaktion

### ISSUE THREAD

**Issue by jonatan2010** [watchone/Downloads#42]
Gibt es einen Grund, weshalb der Hoster Streamtape nicht geht?

Online sind die Links.

**Comment by kasi45** [comment]
@jonatan2010 
hast du noch immer nicht mitbekommen dass deine und von demex2008  geschriebene "Issues" nicht mehr bearbeitet und somit sofort geschlossen werden. 
Bei dem was ihr so schreibt kann man das verstehen. 

STREAMTAPE - ein Problem im URLRESOLVER Addon - und hat nichts mit xShip zu tun

**Comment by jonatan2010** [comment]
Vielen dank für deine Antwort. Sie enthält mehr information als ich jemals vom addoon Ersteller bekommen habe. 

Woher sollte ich als einfacher Nutzer auch wissen, dass es am urlresolver liegt? Dann muss ich mich dort wohl mal melden.

Das Problem, dass der Ersteller die Serien nicht neu einlesen lässt, bleibt aber. Bzw. Soll das nicht eigentlich das addon automatisch machen?

Denn dragonball super hat 130 folgen, die in 5 Staffeln unterteilt sind, aber bei xship alle in einer Staffel, weswegen ab staffel 1 folge 15 (in Wahrheit staffel 2 Folge 1) nichts mehr gefunden wird. Habe ich lang und breit erklärt, scheint der Ersteller aber, warum auch immer, nicht kapieren zu wollen.

**Comment by kasi45** [comment]
@jonatan2010 
Der Ton macht die Musik - und dein Ton (nicht nur hier, auch auf Telegram) hat wohl dafür gesorgt dass du auf dem Index bist. 
Und so wie es aussieht - egal was du schreibst, du bekommst keine Antworten mehr von watchone und nichts was von dir kommt (egal unter welchem Name) wird bearbeitet.  Das gleiche gilt wohl auch für @demex2008

**Comment by jonatan2010** [comment]
Ich habe nur diesen einen account. Habe ihnsogar extra nur wegen diesen Problemen erstellt, ehrlich gesagt. Und was für Telegramm Gruppen? Ich von in keiner xship Telegramm Gruppe, oder sowas.

Welchen ton soll ich haben, wenn beimersten mal, gesagt wird das infos fehlen, ich dann neu reinstelle mit mehr infos und das dann instant geschlossen wird? Ja, nach 5 mal oder so, werde ich dann natürlich sauer, ist ja wohl klar, wenn keine infos wieso, weshalb, warum kommt.

Wie gesagt, du hast mir schon mehr infos gegeben, als der addon Ersteller, was wirklich extrem traurig ist.

**Comment by demex2008** [comment]
Bitte ich habe nur eine Frage gestellt.Was habe ich mit den anderen zutun.Telegramm nutze ich nicht.
Vielen Dank

**Comment by jonatan2010** [comment]
Wo das Problem bei demex ist, weiß ich auch nicht.

Mir persönlich ist das dragonball problem egal, hab alles auf Festplatte. Aber wer weiß, wieviele andere Serien noch von so einem simplen Fehler betroffen sind? Wenn der Ersteller so etwas einfaches nicht hinkriegt, ist er wohl zu unterkomplex für sowas. Er kann ja mal versuchen die Probleme zu beheben und damit zeigen, dass wir falsch liegen.

Bis dahin ist er einfach nur unfähig. Kann ich ja nix für, dass er das nicht gebacken kriegt. Da kann ich nur noch mit dem Kopf schütteln. Ich Frage mich ernsthaft, wie er dieses addon hingekriegt haben will, wenn er schon an einfachsten Problemen scheitert!

**Comment by demex2008** [comment]
Ich hatte nur eine Frage gestellt bezüglich Serienstream . Weiß jetzt echt nicht wo das Problem ist.

**Comment by kasi45** [comment]
Wegen solcher geistigen Höhenflieger wie ihr verschwinden immer wieder Addons von der Bildfläche. Weil deren Ersteller sich solche Ergüsse wie sie von Euch kommen ersparen wollen. 
> Und was für Telegram Gruppen?`
u.a. KODI VAVOO TV Stube - wolltest du auch mich für dumm verkaufen?

**Comment by jonatan2010** [comment]
Aha. Ja, da bin ich drin. Was heißt hier für dumm verkaufen? Weder habe ich behauptet, dass ich in garkeiner Gruppe drin bin, noch hast du präzisiert gehabt, welche du meinst. 

Aber mir ist schon u.a. von einem admin der gruppe bestätigt worden, dass ich dort guten support leiste. Also was willst du von mir?

Also ich bin hier sicher nicht das Problem, sondern die Inkompetenz von dem dude hier, der einfachste Probleme nicht checkt.
